### ISSUE TITLE
CSS changes

### ISSUE THREAD

**Issue by berkbozok** [YordanEvro/TravelCompanion#11]
![Screenshot 2021-04-04 015805](https://user-images.githubusercontent.com/58408904/115597472-4e30ef00-a2a7-11eb-9ffe-bcbfb8d1f567.png)

**Comment by YordanEvro** [comment]
closed by commits on April 22-23rd
![image](https://user-images.githubusercontent.com/48580919/115976260-17bed280-a53a-11eb-84dd-563c3208923b.png)
